name: Context Variables Demo
on: push
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use Context variables
        run: |
          echo "This workflow is triggered by ${{ github.actor }}"
          echo "The repository name is ${{ github.repository}}"
      - name: Prints all variables under github
        run: echo "${{toJson(github)}}"
